require("dotenv").config();
const express = require("express");
const app = express();
const PORT = process.env.PORT;
const authRoute = require("./routes/authRoute");
const bookingRoute = require("./routes/bookingRoute");
app.use(express.json());
app.use("/api/auth/", authRoute);
app.use("/api/booking/", bookingRoute);
app.listen(PORT, () => console.log(`Server running on port:${PORT}`));
